### ISSUE TITLE
problem to download many models on the chaturbate.com

### ISSUE THREAD

**Issue by goodhelper1** [IcaroAugusto/leakgirls-camsite-downloader#3]
Cloudflare is blocking its monitoring program from more than 30 models ...

at chaturbate.com

when consulting the stream link you are obliged to check by human ...

that because I know I have another program that does too and is also broaching.

my tip is to use chaturbate.com api

this is api link

https://chaturbate.com/api/chatvideocontext/Model name/

example

https://chaturbate.com/api/chatvideocontext/lexipoy/

full room json will be issued along with current m3u8 link

you will have all api referring to the room of this model

get this idea

make good use of it =)

**Comment by goodhelper1** [comment]
every time the model is online you will see m3u8 link json

**Comment by IcaroAugusto** [comment]
Thanks for the tip, I will update it to use the api.

**Comment by LillyxNisemon** [comment]
LeakGirls is a badly written, bloated, overpriced piece of software. If you really want to record cam girls, just search the web for 'stream recorder'. There are tons of _free_ programs out there that don't crash constantly and that don't take up 273 MB.

&nbsp;

If for some godawful reason you still want to use this s████y program, rather than giving money to a spammer, you can [download a cracked version for free here](https://disk.yandex.com/d/Q7zvb0Lm06WtZQ). I still don't recommend you do for all of the reasons I just mentioned but, if you really want to use this program for some reason, at least you can without giving money to someone who's always posting spam on Reddit.

&nbsp;

Please feel free to share this link, re-upload the cracked version somewhere else or whatever. I don't even care if you take credit for the crack. Just make sure you include the following message somewhere obvious:

**Stop posting spam on Reddit and I'll stop making cracked versions of LeakGirls!**
